ftp:
  users: 
  - name: hayden
    password: hayden
    home-directory: src/test/resources/ftp/ftphome
  port: 21
  
spring:
  profiles:
    active: mock_image_if,postgres
# website_image_adapter

mock-image-if:
  static-image: test.png