server:
  port: ${PORT:8080}
logging:
  level:
    org.atmosphere: warn

spring:
  mustache:
    check-template-location: false
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

image-server:
  local-directory: /images

# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: false
# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.hdekker